package branch.server;
/**
 * 
 * @author qsh2
 * 
 *         SerialNumberGenerator Generates serial number for the branch server
 *         to use. Serial numbers have the following format. [Transaction
 *         Type][Branch ID][Number] Transaction Type: Transfer (T) Deposit (D)
 *         Withdraw (W) Query (Q) Branch ID: Two digit unique number identifying
 *         the bank. Number: Unique 8 digit number generated by this class.
 *         Identifying the transaction.
 */

public class SerialNumberGenerator {
	private static int currNumber_ = 0;
	private static int branchId_ = -1;

	SerialNumberGenerator(int startFrom, int branchId) {
		currNumber_ = startFrom;
		branchId_ = branchId;
	}

	public static void setBranchId(int branchId) {
		branchId_ = branchId;
	}

	public static void setCurrNumber(int currNumber) {
		currNumber_ = currNumber;
	}
	
	public static synchronized String getNewSerial(Trxn.TransxType type) {
		String serial = "";
		serial += getTransactionCode(type);
		serial += String.format("%02d", branchId_);
		serial += String.format("%08d", currNumber_++);
		return serial;
	}

	private static char getTransactionCode(Trxn.TransxType type) {

		char ch = '\0';

		switch (type) {
		case DEPOSIT:
			ch = 'D';
			break;
		case WITHDRAW:
			ch = 'W';
			break;
		case QUERY:
			ch = 'Q';
			break;
		case TRANSFER:
			ch = 'T';
			break;
		}

		return ch;
	}
}